### PR TITLE
edit pattern validate username

### PR DESCRIPTION
**Pull request by nongsansanee**
please merge

### CODE REVIEW

**Comment by koramit** [comment]
thanks for the PR but `jenny.ko+` or `jenny.ko*` are still valid. Please try again.

**Comment by nongsansanee** [comment]
change validate finished ,Please merge

**Comment by koramit** [comment]
This also make `jenny.soooo+` a valid. Please try again.

**Comment by nongsansanee** [comment]
change validate  round 2 finished ,Please merge

**Comment by koramit** [comment]
Thanks!

**Pull request merged**
